<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $title ?></title>
    <meta name="description" content=<?= $title ?>>
    <meta name="author" content="Conax">
    <meta name="viewport"
    content="minimum-scale=1, initial-scale=1, width=device-width">
    <meta name="theme-color" content="#ffffff">
    <link rel="icon" href="/favicon.ico">
    <link rel="icon" type="image/png" href="/icon-192.png" sizes="192x192">
    <link rel="apple-touch-icon" href="/icon-180.png" sizes="180x180">
    <link rel="manifest" href="/manifest.json">
    <link rel="stylesheet" href="/styles/error.css">
  </head>
  <body>
    <?= $body ?>
  </body>
</html>
