<link rel="stylesheet" href="/styles/error.css">
<h1>JavaScript required</h1>
<hr>
<p>
  This website requires JavaScript in order to work properly.
  <br>
  Make sure that your browser supports JavaScript.
  <br>
  If you're unsure about what browser to use, we recommend
  the latest version of
  <a href="https://www.mozilla.org/en-GB/firefox/download/thanks"
  target="_blank">
  Mozilla Firefox</a>.
</p>
