<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>">
    <meta name="keyword" content="<?= $keywords ?>">
    <meta name="author" content="Conax">
    <meta name="robots" content="all">
    <meta name="viewport"
    content="minimum-scale=1, initial-scale=1, width=device-width">
    <meta name="theme-color" content="#ffffff">
    <link rel="icon" href="/favicon.ico">
    <link rel="icon" type="image/png" href="/icon-192.png" sizes="192x192">
    <link rel="apple-touch-icon" href="/icon-180.png" sizes="180x180">
    <link rel="manifest" href="/manifest.json">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preload" as="style"
    onload="this.onload=null;this.rel='stylesheet'"
    href="https://fonts.googleapis.com/css2?family=Encode+Sans:wght@400;700&display=swap">
    <link rel="preload" as="style"
    onload="this.onload=null;this.rel='stylesheet'"
    href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script async
    src="https://www.googletagmanager.com/gtag/js?id=G-4GFYMNVG6D">
    </script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag("js", new Date());
      gtag("config", "G-4GFYMNVG6D");
    </script>
  </head>
  <body>
    <noscript>
      <?= $noscript ?>
    </noscript>
    <script src="/app/main.bundle.js"></script>
    <div id="root"></div>
    <script>
      window.conax.load(<?= $data ?>);
    </script>
  </body>
</html>
